import React, { Suspense } from "react";
import type { Metadata } from "next";
import PostList from "@/components/post-list";

export const metadata: Metadata = {
  title: "My Posts",
  description: "Generated by create next app",
};

export default async function Page() {
  return (
    <main className="text-center pt-16 px-5">
      <h1 className="text-4xl md:text-5xl font-bold mb-5">Posts Page</h1>

      <Suspense fallback={<p className="text-2xl font-semibold">Loading...</p>}>
        <PostList />
      </Suspense>
    </main>
  );
}
